addtrainwindow.o
administrate.o
benchmark.o
binfile.o
demo.o
functs.o
main.o
mainwindow.o
searchoptionswindow.o
table.o
tests.o
textfile.o
train.o
moc_addtrainwindow.o
moc_administrate.o
moc_demo.o
moc_mainwindow.o
moc_searchoptionswindow.o
moc_tests.o
